# Generated by Django 4.0.3 on 2022-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_parameter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('tracking_no', models.CharField(max_length=50)),
                ('media', models.CharField(max_length=25)),
                ('parish', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=35)),
                ('permit_no', models.CharField(max_length=60)),
                ('action_type', models.CharField(max_length=75)),
                ('status', models.CharField(max_length=15)),
                ('received_date', models.DateField()),
                ('status_date', models.DateField()),
                ('effective_start_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
