# Generated by Django 4.0.3 on 2022-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_permit_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permit_new',
            new_name='NewPermit',
        ),
    ]
