# Generated by Django 4.0.3 on 2022-03-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_permit_new_newpermit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpermit',
            old_name='action_type',
            new_name='ACTION_TYPE',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='tracking_no',
            new_name='ACT_TRACKING_NO',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='effective_start_date',
            new_name='EFFECTIVE_START_DATE',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='expiration_date',
            new_name='EXPIRATION_DATE',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='ai',
            new_name='MASTER_AI_ID',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='name',
            new_name='MASTER_AI_NAME',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='media',
            new_name='MEDIA',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='parish',
            new_name='PARIST',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='permit_no',
            new_name='PERMIT_NO',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='received_date',
            new_name='RECEIVED_DATE',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='status',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='status_date',
            new_name='STATUS_DATE',
        ),
        migrations.RenameField(
            model_name='newpermit',
            old_name='writer',
            new_name='WRITER',
        ),
    ]
