# Generated by Django 4.0.3 on 2022-03-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_action_type_newpermit_action_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpermit',
            old_name='PARIST',
            new_name='PARISH',
        ),
    ]
