# Generated by Django 4.0.3 on 2022-03-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_parist_newpermit_parish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MASTER_AI_ID', models.IntegerField()),
                ('MASTER_AI_NAME', models.CharField(max_length=150)),
                ('ACT_TRACKING_NO', models.CharField(max_length=50)),
                ('MEDIA', models.CharField(max_length=25)),
                ('PARISH', models.CharField(max_length=30)),
                ('WRITER', models.CharField(max_length=35)),
                ('PERMIT_NO', models.CharField(max_length=60)),
                ('ACTION_TYPE', models.CharField(max_length=75)),
                ('STATUS', models.CharField(max_length=15)),
                ('RECEIVED_DATE', models.DateField(blank=True, null=True)),
                ('STATUS_DATE', models.DateField(blank=True, null=True)),
                ('EFFECTIVE_START_DATE', models.DateField(blank=True, null=True)),
                ('EXPIRATION_DATE', models.DateField(blank=True, null=True)),
                ('date_uploaded', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewPermit',
        ),
    ]
